services:
  mosquitto:
    container_name: 'redes-mosquitto'
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - '1883:1883'

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: 'redes-duckdns'
    network_mode: host
    environment:
      - SUBDOMAINS=${DOMAIN_NAME}
      - TOKEN=${DUCKDNS_TOKEN}
    volumes:
      - ./duckdns/config:/config
