services:
  mosquitto:
    container_name: 'seg-redes-mosquitto'
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
      - '8883:8883'
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: unless-stopped
    volumes:
      - './mosquitto/config/:/mosquitto/config/'
      - './mosquitto/certs/:/mosquitto/certs/'
      - './init_mosquitto.sh:/init_mosquitto.sh'
    entrypoint: ["/bin/sh", "/init_mosquitto.sh"]

  duckdns:
    container_name: 'seg-redes-duckdns'
    image: lscr.io/linuxserver/duckdns:latest
    network_mode: host
    environment:
      - SUBDOMAINS=${DOMAIN_NAME}
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped
    volumes:
      - ./duckdns/config:/config
